// supabase/functions/generate-note/index.ts
// Edge Function Supabase — GenerateNoteAI
// Sécurité : la clé OpenAI reste côté serveur uniquement (variable d'environnement)
// FlutterFlow appelle cet endpoint avec le JWT Supabase de l'utilisateur connecté

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// ─── Types ───────────────────────────────────────────────────────────────────

interface GenerateNoteRequest {
  patient_nom: string;
    patient_prenom: string;
      date_visite: string;          // ISO 8601 — ex: "2025-06-15"
        type_soin: string;            // ex: "Soins podologiques à domicile"
          observations: string;         // texte libre saisi par la clinicienne
            antecedents?: string;         // facultatif
              medicaments?: string;         // facultatif
                rendez_vous_id?: string;      // UUID — si fourni, la note sera liée au RDV
                }

                interface GenerateNoteResponse {
                  note: string;
                    tokens_used?: number;
                    }

                    // ─── CORS Headers ────────────────────────────────────────────────────────────

                    const corsHeaders = {
                      "Access-Control-Allow-Origin": "*",
                        "Access-Control-Allow-Headers":
                            "authorization, x-client-info, apikey, content-type",
                              "Access-Control-Allow-Methods": "POST, OPTIONS",
                              };

                              // ─── Handler principal ───────────────────────────────────────────────────────

                              serve(async (req: Request) => {
                                // Preflight CORS
                                  if (req.method === "OPTIONS") {
                                      return new Response("ok", { headers: corsHeaders });
                                        }

                                          try {
                                              // 1. Vérifier l'authentification via JWT Supabase
                                                  const authHeader = req.headers.get("Authorization");
                                                      if (!authHeader) {
                                                            return new Response(
                                                                    JSON.stringify({ error: "Non autorisé : en-tête Authorization manquant" }),
                                                                            { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                  );
                                                                                      }

                                                                                          // Initialiser le client Supabase avec le JWT de l'utilisateur
                                                                                              const supabaseClient = createClient(
                                                                                                    Deno.env.get("SUPABASE_URL") ?? "",
                                                                                                          Deno.env.get("SUPABASE_ANON_KEY") ?? "",
                                                                                                                { global: { headers: { Authorization: authHeader } } }
                                                                                                                    );
                                                                                                                    
                                                                                                                        // Vérifier que le token est valide
                                                                                                                            const { data: { user }, error: authError } = await supabaseClient.auth.getUser();
                                                                                                                                if (authError || !user) {
                                                                                                                                      return new Response(
                                                                                                                                              JSON.stringify({ error: "Non autorisé : token invalide ou expiré" }),
                                                                                                                                                      { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                                                                                            );
                                                                                                                                                                }
                                                                                                                                                                
                                                                                                                                                                    // 2. Parser le corps de la requête
                                                                                                                                                                        const body: GenerateNoteRequest = await req.json();
                                                                                                                                                                        
                                                                                                                                                                            // Validation minimale
                                                                                                                                                                                if (!body.patient_nom || !body.patient_prenom || !body.observations || !body.date_visite) {
                                                                                                                                                                                      return new Response(
                                                                                                                                                                                              JSON.stringify({ error: "Champs obligatoires manquants : patient_nom, patient_prenom, observations, date_visite" }),
                                                                                                                                                                                                      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                                                                                                                                            );
                                                                                                                                                                                                                }
                                                                                                                                                                                                                
                                                                                                                                                                                                                    // 3. Construire le prompt pour OpenAI
                                                                                                                                                                                                                        const systemPrompt = `Tu es un assistant clinique spécialisé pour podologues et infirmières au Québec.
                                                                                                                                                                                                                        Tu rédiges des notes cliniques professionnelles en français, adaptées aux visites à domicile.
                                                                                                                                                                                                                        Tes notes sont claires, concises, médicalement précises et conformes aux standards de documentation clinique québécois.
                                                                                                                                                                                                                        Tu n'inventes aucune information — tu te bases uniquement sur les données fournies.
                                                                                                                                                                                                                        Longueur cible : 150-250 mots. Format : paragraphes continus (pas de listes à puces).`;
                                                                                                                                                                                                                        
                                                                                                                                                                                                                            const userPrompt = `Rédige une note clinique pour la visite suivante :
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            Patient : ${body.patient_prenom} ${body.patient_nom}
                                                                                                                                                                                                                            Date de visite : ${body.date_visite}
                                                                                                                                                                                                                            Type de soin : ${body.type_soin}
                                                                                                                                                                                                                            ${body.antecedents ? `Antécédents pertinents : ${body.antecedents}` : ""}
                                                                                                                                                                                                                            ${body.medicaments ? `Médicaments actuels : ${body.medicaments}` : ""}
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            Observations de la clinicienne :
                                                                                                                                                                                                                            ${body.observations}
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            Rédige une note clinique professionnelle en français pour documenter cette visite.`;
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                // 4. Appeler OpenAI (clé UNIQUEMENT côté serveur)
                                                                                                                                                                                                                                    const openaiApiKey = Deno.env.get("OPENAI_API_KEY");
                                                                                                                                                                                                                                        if (!openaiApiKey) {
                                                                                                                                                                                                                                              console.error("OPENAI_API_KEY non configurée dans les secrets Supabase");
                                                                                                                                                                                                                                                    return new Response(
                                                                                                                                                                                                                                                            JSON.stringify({ error: "Configuration serveur manquante" }),
                                                                                                                                                                                                                                                                    { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                  const openaiResponse = await fetch("https://api.openai.com/v1/chat/completions", {
                                                                                                                                                                                                                                                                                        method: "POST",
                                                                                                                                                                                                                                                                                              headers: {
                                                                                                                                                                                                                                                                                                      "Authorization": `Bearer ${openaiApiKey}`,
                                                                                                                                                                                                                                                                                                              "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                          body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                  model: "gpt-4o-mini",
                                                                                                                                                                                                                                                                                                                                          temperature: 0.3,
                                                                                                                                                                                                                                                                                                                                                  max_tokens: 500,
                                                                                                                                                                                                                                                                                                                                                          messages: [
                                                                                                                                                                                                                                                                                                                                                                    { role: "system", content: systemPrompt },
                                                                                                                                                                                                                                                                                                                                                                              { role: "user", content: userPrompt },
                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                            }),
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    if (!openaiResponse.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                          const errorText = await openaiResponse.text();
                                                                                                                                                                                                                                                                                                                                                                                                                console.error("Erreur OpenAI:", openaiResponse.status, errorText);
                                                                                                                                                                                                                                                                                                                                                                                                                      return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                              JSON.stringify({ error: "Erreur lors de la génération de la note" }),
                                                                                                                                                                                                                                                                                                                                                                                                                                      { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const openaiData = await openaiResponse.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const noteGeneree = openaiData.choices?.[0]?.message?.content?.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!noteGeneree) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          JSON.stringify({ error: "Réponse OpenAI vide ou invalide" }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 5. (Optionnel) Journaliser l'utilisation dans Supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Cette section permet de tracker les tokens et associer la note au RDV
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const serviceClient = createClient(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Deno.env.get("SUPABASE_URL") ?? "",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await serviceClient.from("ia_logs").insert({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  user_id: user.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fonction: "generate-note",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  tokens_entree: openaiData.usage?.prompt_tokens ?? 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          tokens_sortie: openaiData.usage?.completion_tokens ?? 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  rendez_vous_id: body.rendez_vous_id ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          created_at: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (logError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Ne pas bloquer la réponse si le log échoue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.warn("Impossible de journaliser l'usage IA:", logError);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 6. Retourner la note générée
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const response: GenerateNoteResponse = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  note: noteGeneree,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tokens_used: openaiData.usage?.total_tokens,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      JSON.stringify(response),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status: 200,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            headers: { ...corsHeaders, "Content-Type": "application/json" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error("Erreur inattendue:", error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      JSON.stringify({ error: "Erreur interne du serveur" }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
